//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DebuggerUI/DBGNode.h>

@class DBGInteractiveSceneView, NSColor, SCNNode;

@interface DBGBorderNode : DBGNode
{
    BOOL _dashed;
    NSColor *_borderColor;
    double _borderOpacity;
    double _lineWidth;
    DBGInteractiveSceneView *_sceneView;
    SCNNode *_topLeft;
    SCNNode *_bottomLeft;
    SCNNode *_bottomRight;
    SCNNode *_topRight;
    DBGNode *_topEdgeNode;
    DBGNode *_leftEdgeNode;
    DBGNode *_bottomEdgeNode;
    DBGNode *_rightEdgeNode;
    struct CGRect _borderRect;
    struct CGRect _clippingRect;
}

+ (id)borderNodeWithRect:(struct CGRect)arg1 addToParentNode:(id)arg2 sceneView:(id)arg3;
@property(retain, nonatomic) DBGNode *rightEdgeNode; // @synthesize rightEdgeNode=_rightEdgeNode;
@property(retain, nonatomic) DBGNode *bottomEdgeNode; // @synthesize bottomEdgeNode=_bottomEdgeNode;
@property(retain, nonatomic) DBGNode *leftEdgeNode; // @synthesize leftEdgeNode=_leftEdgeNode;
@property(retain, nonatomic) DBGNode *topEdgeNode; // @synthesize topEdgeNode=_topEdgeNode;
@property(retain, nonatomic) SCNNode *topRight; // @synthesize topRight=_topRight;
@property(retain, nonatomic) SCNNode *bottomRight; // @synthesize bottomRight=_bottomRight;
@property(retain, nonatomic) SCNNode *bottomLeft; // @synthesize bottomLeft=_bottomLeft;
@property(retain, nonatomic) SCNNode *topLeft; // @synthesize topLeft=_topLeft;
@property(nonatomic) __weak DBGInteractiveSceneView *sceneView; // @synthesize sceneView=_sceneView;
@property(nonatomic) BOOL dashed; // @synthesize dashed=_dashed;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) double borderOpacity; // @synthesize borderOpacity=_borderOpacity;
@property(retain, nonatomic) NSColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) struct CGRect clippingRect; // @synthesize clippingRect=_clippingRect;
@property(nonatomic) struct CGRect borderRect; // @synthesize borderRect=_borderRect;
- (void).cxx_destruct;
- (void)setOpacity:(double)arg1;
@property(readonly, nonatomic) struct CGRect effectiveBorderRect;
- (void)updateEffectiveBorderRect;
- (void)setShineThroughOpacity:(double)arg1;
- (void)setGeometryShinesThrough:(BOOL)arg1;
- (void)unclip;
- (void)clipToLocalRect:(struct CGRect)arg1 originalPlaneSize:(struct CGSize)arg2;
- (void)updateLines;
- (void)setupLines;
- (void)setRenderingOrder:(long long)arg1;
- (id)initWithBorderRect:(struct CGRect)arg1 addToParentNode:(id)arg2 sceneView:(id)arg3;

@end

