//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBBasePreviewRecipe.h"

@class IBCocoaTouchDeviceSubtype, IBCocoaTouchIdiom, IBUISimulatedOrientationMetrics;

@interface IBCocoaTouchPreviewRecipe : IBBasePreviewRecipe
{
    IBCocoaTouchIdiom *_idiom;
    IBCocoaTouchDeviceSubtype *_deviceSubtype;
    IBUISimulatedOrientationMetrics *_orientationMetrics;
}

@property(retain) IBUISimulatedOrientationMetrics *orientationMetrics; // @synthesize orientationMetrics=_orientationMetrics;
@property(retain) IBCocoaTouchDeviceSubtype *deviceSubtype; // @synthesize deviceSubtype=_deviceSubtype;
@property(retain) IBCocoaTouchIdiom *idiom; // @synthesize idiom=_idiom;
- (void).cxx_destruct;
- (id)memberConfiguration;
- (id)targetRuntime;
- (id)screenMetrics;
- (id)propertyListRepresentation;
- (id)initWithPropertyList:(id)arg1;
- (id)initWithLanguage:(id)arg1 idiom:(id)arg2 deviceSubtype:(id)arg3 orientationMetrics:(id)arg4;

@end

