//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IBDeviceSubtype.h"

@class IBUIScreenMetrics;

@interface IBCocoaTouchDeviceSubtype : IBDeviceSubtype
{
    IBUIScreenMetrics *_screenMetrics;
}

+ (id)subtypeWithIdentifier:(id)arg1 name:(id)arg2 screenMetrics:(id)arg3;
@property(readonly, nonatomic) IBUIScreenMetrics *screenMetrics; // @synthesize screenMetrics=_screenMetrics;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1 name:(id)arg2 screenMetrics:(id)arg3;

@end

