//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DYBuffer.h"

@protocol DYPMTLBuffer <DYBuffer>
@property(readonly, nonatomic) BOOL isBytesOnly;
@property(readonly, nonatomic) BOOL zeroFill;
@property(readonly, nonatomic) unsigned long long length;
@end

