//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUDebuggerController.h"

#import "DYPShaderUpdaterDelegate.h"

@class DVTFilePath, DVTObservingToken, DYMTLAnalyzerArchiveVisitor, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface GPUMTLDebuggerController : GPUDebuggerController <DYPShaderUpdaterDelegate>
{
    DYMTLAnalyzerArchiveVisitor *_analyzerVisitor;
    DVTObservingToken *_overviewSamplesObserver;
    NSMutableArray *_overviewSampleArray;
    BOOL _finalizedOverview;
    DVTFilePath *_defaultLibraryPath;
    BOOL _updateDefaultLibrary;
    id <DYPDebuggerControllerProxy> _platformDebuggerController;
    id <DYPShaderUpdater> _shaderUpdater;
    BOOL _shadersUpdatable;
}

+ (id)assetBundle;
@property(nonatomic) BOOL shadersUpdatable; // @synthesize shadersUpdatable=_shadersUpdatable;
- (void).cxx_destruct;
- (void)defaultLibraryUpdateRequested:(CDUnknownBlockType)arg1;
- (void)setInfoDictForProgram:(unsigned long long)arg1 dict:(id)arg2 container:(unsigned long long)arg3;
- (id)infoDictForProgram:(unsigned long long)arg1 container:(unsigned long long)arg2;
- (void)shaderUpdatedWithStatus:(BOOL)arg1 resource:(id)arg2;
- (BOOL)supportsDebugBarShaderUpdate;
- (BOOL)analyzeStoredCaptureArchive;
- (void)onRequestProfilerData:(id)arg1;
- (BOOL)isDisassemblerAvailable;
- (id)runShaderProfiler;
- (void)handleInferiorSessionActiveState;
- (void)traceSessionEstablishedWithNewArchive:(BOOL)arg1;
- (BOOL)_configureInvestigatorWithCaseConfigData:(id)arg1;
- (id)createProgramPerformanceReportProvider:(id)arg1;
- (id)createInvestigatorReportProvider:(id)arg1;
- (void)createReportWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)updateShaders;
- (void)handleDocumentChanged:(id)arg1 currentAPIItem:(id)arg2;
- (void)resetResourceManagerWithResourceStreamer:(id)arg1;
- (BOOL)handleCaptureSessionFinalization:(id)arg1;
- (void)setupCaptureSessionInfoWithArchive:(id)arg1;
- (void)handleAppSessionTransportMessage:(id)arg1;
- (void)_unarchiveReports;
- (void)setupGuestAppSession:(id)arg1;
- (id)newGuestAppSessionWithGuestApp:(id)arg1 device:(id)arg2 deferLaunch:(BOOL)arg3 error:(id *)arg4;
- (BOOL)isOfflineShaderInLoadedCapture;
- (void)createModelFactory;
- (void)setDeviceInfo:(id)arg1;
- (BOOL)supportsInvestigator;
- (void)primitiveInvalidate;
- (id)init;
- (id)appRunnableLocation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

