//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPUVariablesViewContentProvider.h"

#import "DYPVariablesViewContentProviderDelegate.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface GPUMTLVariablesViewContentProvider : GPUVariablesViewContentProvider <DYPVariablesViewContentProviderDelegate>
{
    id <DYPVariablesViewContentProvider> _platformVariablesView;
    NSString *_sessionID;
}

@property(readonly) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (void).cxx_destruct;
- (id)imageToUseInDefaultQuickLookForNode:(id)arg1;
- (id)imageForNode:(id)arg1;
- (void)provideScopeChoices:(id)arg1;
- (id)currentlyDisplayedResourceItems;
- (id)defaultImageWithIssueType:(int)arg1 ofSize:(unsigned long long)arg2;
- (id)cachedImageWithName:(id)arg1 fromBundle:(id)arg2;
- (BOOL)isRuntimeOSAppleInternal;
- (void)addVariableNodeFromDataValue:(id)arg1 type:(unsigned long long)arg2 recipientArray:(id)arg3;
- (void)bubbleUpChangeStatusHighlighting:(id)arg1;
- (void)setEmptyVarView;
- (id)newStateValue;
- (void)addAnalyzerFindingContent:(id)arg1 toArray:(id)arg2;
- (void)_updateFilteredListForAuto;
- (void)_updateFilteredListForContextInfo;
- (void)_updateFilteredListForAllObjects;
- (void)_updateFilteredListForBoundObjects;
- (void)_updateFilteredListForCommandEncoder;
- (void)updateFilteredList;
- (void)updateCurrentLocation:(id)arg1;
- (void)primitiveInvalidate;
- (void)setDebuggerController:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) int comparisonMode;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) int textMode;

@end

