//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, IDEWorkspace, NSString, NSURL, SKResourceManager, SKWorkspacePreferences;

@interface SKWorkspace : NSObject <DVTInvalidation>
{
    SKResourceManager *_resourceManager;
    SKWorkspacePreferences *_preferences;
    IDEWorkspace *_ideWorkspace;
    NSURL *_url;
}

+ (id)workspaceForIDEWorkspace:(id)arg1;
+ (void)initialize;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) IDEWorkspace *ideWorkspace; // @synthesize ideWorkspace=_ideWorkspace;
- (void).cxx_destruct;
@property(readonly, nonatomic) SKWorkspacePreferences *preferences; // @synthesize preferences=_preferences;
@property(readonly, nonatomic) SKResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
- (void)primitiveInvalidate;
- (id)initWithIDEWorkspace:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

